import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../core/theme/app_typography.dart';
import '../../core/widgets/glass_card.dart';
import '../../core/widgets/offline_view.dart';
import '../../data/services/llm_service.dart';
import '../notes/notes_controller.dart';
import 'care_plan_model.dart';
import 'care_plan_prompt.dart';

final _llmProvider = Provider((_) => LlmService());

/// How the generated plan is laid out: readable stacked cards (default) or the
/// classic 6-column nursing-care-plan grid (Assessment · Diagnosis · Outcomes ·
/// Interventions · Rationale · Evaluation).
enum _PlanView { card, grid }

/// Generates a complete Nursing Care Plan (ADPIE + rationale) from a patient
/// situation the user describes. Separate from the Clinical Case feature.
class CarePlanScreen extends ConsumerStatefulWidget {
  const CarePlanScreen({super.key});

  @override
  ConsumerState<CarePlanScreen> createState() => _CarePlanScreenState();
}

class _CarePlanScreenState extends ConsumerState<CarePlanScreen> {
  final _input = TextEditingController();
  bool _loading = false;
  bool _offline = false;

  /// Parsed plan when the AI returned valid JSON; null otherwise.
  CarePlan? _plan;

  /// Raw reply kept only when parsing failed, so the user still sees something.
  String? _rawFallback;

  _PlanView _view = _PlanView.card;

  static const _example =
      'Patient complains of elevated temperature (38.9°C), chills, and '
      'fatigue. Vital signs unstable: HR 112, RR 24, BP 100/60. Skin warm '
      'and flushed.';

  @override
  void dispose() {
    _input.dispose();
    super.dispose();
  }

  Future<void> _generate() async {
    final situation = _input.text.trim();
    if (situation.isEmpty || _loading) return;
    FocusScope.of(context).unfocus();
    setState(() {
      _loading = true;
      _offline = false;
      _plan = null;
      _rawFallback = null;
    });
    try {
      final result = await ref.read(_llmProvider).chat(
        temperature: 0.4,
        [
          {'role': 'system', 'content': carePlanSystemPrompt},
          {'role': 'user', 'content': 'PATIENT SITUATION:\n$situation'},
        ],
      );
      final parsed = CarePlan.tryParse(result);
      if (mounted) {
        setState(() {
          if (parsed != null) {
            _plan = parsed;
          } else {
            _rawFallback = result.trim();
          }
        });
      }
    } on OfflineException {
      if (mounted) setState(() => _offline = true);
    } catch (_) {
      if (mounted) {
        setState(() => _rawFallback =
            "Couldn't generate a care plan. Something went wrong reaching "
            'the AI. Please check your connection and try again.');
      }
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }

  void _saveToNotes() {
    final body = _plan?.toMarkdown() ?? _rawFallback;
    if (body == null) return;
    final seed = _plan?.summary.isNotEmpty == true
        ? _plan!.summary
        : _input.text.trim().split(RegExp(r'[.\n]')).first;
    final title = 'Care Plan — $seed';
    ref.read(notesProvider.notifier).add(
          title: title.length > 60 ? '${title.substring(0, 57)}…' : title,
          body: body,
        );
    ScaffoldMessenger.of(context)
        .showSnackBar(const SnackBar(content: Text('Saved to Notes ✅')));
  }

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final text = Theme.of(context).textTheme;
    final hasResult = _plan != null || _rawFallback != null;

    if (_offline) {
      return Scaffold(
        appBar: AppBar(title: const Text('Nursing Care Plan')),
        body: OfflineView(
          message: 'Care plans are generated by AI and need internet.',
          onRetry: () => setState(() => _offline = false),
        ),
      );
    }

    return Scaffold(
      appBar: AppBar(
        title: const Text('Nursing Care Plan'),
        actions: [
          if (hasResult && !_loading)
            IconButton(
              tooltip: 'Save to Notes',
              onPressed: _saveToNotes,
              icon: const Icon(Icons.bookmark_add_outlined),
            ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('Describe the patient',
                style: text.titleSmall?.copyWith(color: scheme.onSurface)),
            const SizedBox(height: 4),
            Text(
              'Chief complaint, cues, and vital signs. The AI builds a full '
              'ADPIE care plan with rationale.',
              style: text.bodySmall?.copyWith(
                  color: scheme.onSurface.withValues(alpha: 0.7)),
            ),
            const SizedBox(height: 12),
            TextField(
              controller: _input,
              minLines: 4,
              maxLines: 8,
              style: text.bodyLarge,
              textCapitalization: TextCapitalization.sentences,
              decoration: InputDecoration(
                hintText: _example,
                filled: true,
                fillColor: scheme.surface,
                border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(16),
                    borderSide: BorderSide(color: scheme.outline)),
                enabledBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(16),
                    borderSide: BorderSide(color: scheme.outline)),
                focusedBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(16),
                    borderSide: BorderSide(color: scheme.primary, width: 2)),
                contentPadding: const EdgeInsets.all(16),
              ),
            ),
            const SizedBox(height: 8),
            // Quick-fill example.
            Align(
              alignment: Alignment.centerLeft,
              child: TextButton.icon(
                onPressed: () => setState(() => _input.text = _example),
                icon: const Icon(Icons.bolt, size: 18),
                label: const Text('Use example'),
              ),
            ),
            const SizedBox(height: 8),
            SizedBox(
              width: double.infinity,
              child: FilledButton.icon(
                onPressed: _loading ? null : _generate,
                style: FilledButton.styleFrom(
                  backgroundColor: scheme.primary,
                  foregroundColor: scheme.onPrimary,
                  padding: const EdgeInsets.symmetric(vertical: 16),
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(14)),
                ),
                icon: _loading
                    ? const SizedBox.shrink()
                    : const Icon(Icons.assignment_outlined),
                label: _loading
                    ? SizedBox(
                        height: 22,
                        width: 22,
                        child: CircularProgressIndicator(
                            strokeWidth: 2.5, color: scheme.onPrimary))
                    : const Text('Generate Care Plan'),
              ),
            ),
            const SizedBox(height: 20),

            // ── View toggle (only when we have a structured plan) ────────────
            if (_plan != null) ...[
              Center(
                child: SegmentedButton<_PlanView>(
                  segments: const [
                    ButtonSegment(
                      value: _PlanView.card,
                      icon: Icon(Icons.view_agenda_outlined),
                      label: Text('Card'),
                    ),
                    ButtonSegment(
                      value: _PlanView.grid,
                      icon: Icon(Icons.grid_on_outlined),
                      label: Text('Grid'),
                    ),
                  ],
                  selected: {_view},
                  onSelectionChanged: (s) => setState(() => _view = s.first),
                ),
              ),
              const SizedBox(height: 16),
              if (_view == _PlanView.card)
                _CardView(plan: _plan!)
              else
                _GridView(plan: _plan!),
            ],

            // ── Fallback: model didn't return parseable JSON ─────────────────
            if (_rawFallback != null)
              GlassCard(
                tint: scheme.primary,
                padding: const EdgeInsets.all(20),
                child: MarkdownBody(
                  data: _rawFallback!,
                  styleSheet: MarkdownStyleSheet(
                    p: text.bodyMedium,
                    h2: text.titleLarge?.copyWith(color: scheme.primary),
                    h3: text.titleMedium?.copyWith(color: scheme.primary),
                    strong: TextStyle(
                        fontFamily: AppFonts.sans,
                        fontWeight: FontWeight.w700,
                        color: scheme.onSurface),
                    listBullet: text.bodyMedium,
                    em: text.bodyMedium
                        ?.copyWith(fontStyle: FontStyle.italic),
                  ),
                ),
              ),

            const SizedBox(height: 24),
            const _AboutCarePlans(),
          ],
        ),
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Card view — one labeled card per nursing diagnosis. Best for phone reading.
// ─────────────────────────────────────────────────────────────────────────────
class _CardView extends StatelessWidget {
  const _CardView({required this.plan});

  final CarePlan plan;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        for (var i = 0; i < plan.rows.length; i++) ...[
          _DiagnosisCard(index: i, row: plan.rows[i]),
          if (i != plan.rows.length - 1) const SizedBox(height: 16),
        ],
      ],
    );
  }
}

class _DiagnosisCard extends StatelessWidget {
  const _DiagnosisCard({required this.index, required this.row});

  final int index;
  final CarePlanDiagnosis row;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final text = Theme.of(context).textTheme;

    return GlassCard(
      tint: scheme.primary,
      padding: const EdgeInsets.all(18),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
            decoration: BoxDecoration(
              color: scheme.primary.withValues(alpha: 0.18),
              borderRadius: BorderRadius.circular(8),
            ),
            child: Text('NURSING DIAGNOSIS ${index + 1}',
                style: text.labelMedium?.copyWith(
                    color: scheme.primary,
                    fontWeight: FontWeight.w700,
                    letterSpacing: 0.6)),
          ),
          const SizedBox(height: 12),
          _Section(
            label: 'Assessment',
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                if (row.subjective.isNotEmpty)
                  _LabeledLine('Subjective', row.subjective),
                if (row.objective.isNotEmpty)
                  _LabeledLine('Objective', row.objective),
              ],
            ),
          ),
          _Section(
            label: 'Diagnosis',
            child: Text(row.diagnosis, style: text.bodyMedium),
          ),
          _Section(
            label: 'Outcomes',
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                if (row.shortTermOutcome.isNotEmpty)
                  _LabeledLine('Short-term', row.shortTermOutcome),
                if (row.longTermOutcome.isNotEmpty)
                  _LabeledLine('Long-term', row.longTermOutcome),
              ],
            ),
          ),
          _Section(
            label: 'Interventions & Rationale',
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                for (var j = 0; j < row.interventions.length; j++)
                  Padding(
                    padding: EdgeInsets.only(
                        bottom: j == row.interventions.length - 1 ? 0 : 10),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text('${j + 1}. ${row.interventions[j].action}',
                            style: text.bodyMedium
                                ?.copyWith(fontWeight: FontWeight.w600)),
                        const SizedBox(height: 2),
                        Padding(
                          padding: const EdgeInsets.only(left: 16),
                          child: Text(
                            'Rationale: ${row.interventions[j].rationale}',
                            style: text.bodySmall?.copyWith(
                                fontStyle: FontStyle.italic,
                                color: scheme.onSurface
                                    .withValues(alpha: 0.75)),
                          ),
                        ),
                      ],
                    ),
                  ),
              ],
            ),
          ),
          _Section(
            label: 'Evaluation',
            last: true,
            child: Text(row.evaluation, style: text.bodyMedium),
          ),
        ],
      ),
    );
  }
}

/// A titled block inside a diagnosis card.
class _Section extends StatelessWidget {
  const _Section({required this.label, required this.child, this.last = false});

  final String label;
  final Widget child;
  final bool last;

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final text = Theme.of(context).textTheme;
    return Padding(
      padding: EdgeInsets.only(bottom: last ? 0 : 14),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(label.toUpperCase(),
              style: text.labelSmall?.copyWith(
                  color: scheme.primary,
                  fontWeight: FontWeight.w700,
                  letterSpacing: 0.5)),
          const SizedBox(height: 4),
          child,
        ],
      ),
    );
  }
}

/// "Subjective: …" inline label + value.
class _LabeledLine extends StatelessWidget {
  const _LabeledLine(this.label, this.value);

  final String label;
  final String value;

  @override
  Widget build(BuildContext context) {
    final text = Theme.of(context).textTheme;
    return Padding(
      padding: const EdgeInsets.only(bottom: 4),
      child: RichText(
        text: TextSpan(
          style: text.bodyMedium,
          children: [
            TextSpan(
                text: '$label: ',
                style: const TextStyle(fontWeight: FontWeight.w700)),
            TextSpan(text: value),
          ],
        ),
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Grid view — the literal 6-column table from the screenshot, scrolled
// horizontally so every column keeps a readable width on a phone.
// ─────────────────────────────────────────────────────────────────────────────
class _GridView extends StatelessWidget {
  const _GridView({required this.plan});

  final CarePlan plan;

  static const _headers = [
    'Assessment',
    'Diagnosis',
    'Outcomes',
    'Interventions',
    'Rationale',
    'Evaluation',
  ];

  // Per-column widths (logical px). A real Table sizes each row to its tallest
  // cell, so multi-line text wraps and grows the row instead of overflowing.
  static const _widths = <int, TableColumnWidth>{
    0: FixedColumnWidth(180), // Assessment
    1: FixedColumnWidth(150), // Diagnosis
    2: FixedColumnWidth(160), // Outcomes
    3: FixedColumnWidth(180), // Interventions
    4: FixedColumnWidth(180), // Rationale
    5: FixedColumnWidth(150), // Evaluation
  };

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final text = Theme.of(context).textTheme;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Icon(Icons.swipe,
                size: 16, color: scheme.onSurface.withValues(alpha: 0.6)),
            const SizedBox(width: 6),
            Text('Swipe sideways to see all columns',
                style: text.bodySmall
                    ?.copyWith(color: scheme.onSurface.withValues(alpha: 0.6))),
          ],
        ),
        const SizedBox(height: 8),
        ClipRRect(
          borderRadius: BorderRadius.circular(16),
          child: SingleChildScrollView(
            scrollDirection: Axis.horizontal,
            child: Table(
              defaultColumnWidth: const FixedColumnWidth(160),
              columnWidths: _widths,
              border: TableBorder.all(color: scheme.outline, width: 1),
              defaultVerticalAlignment: TableCellVerticalAlignment.top,
              children: [
                // Header row.
                TableRow(
                  decoration: BoxDecoration(
                      color: scheme.primary.withValues(alpha: 0.18)),
                  children: [
                    for (final h in _headers)
                      _CellBox(
                        child: Text(h,
                            style: text.labelLarge?.copyWith(
                                color: scheme.primary,
                                fontWeight: FontWeight.w700)),
                      ),
                  ],
                ),
                // One row per nursing diagnosis.
                for (final r in plan.rows)
                  TableRow(
                    children: [
                      _CellBox(child: Text(_assessment(r), style: text.bodySmall)),
                      _CellBox(child: Text(r.diagnosis, style: text.bodySmall)),
                      _CellBox(child: Text(r.outcomes, style: text.bodySmall)),
                      _CellBox(child: _numbered(r, text, rationale: false)),
                      _CellBox(child: _numbered(r, text, rationale: true)),
                      _CellBox(child: Text(r.evaluation, style: text.bodySmall)),
                    ],
                  ),
              ],
            ),
          ),
        ),
      ],
    );
  }

  static String _assessment(CarePlanDiagnosis r) {
    final parts = <String>[
      if (r.subjective.isNotEmpty) 'S: ${r.subjective}',
      if (r.objective.isNotEmpty) 'O: ${r.objective}',
    ];
    return parts.join('\n\n');
  }

  /// Interventions and Rationale share the same numbering so the two columns
  /// line up the way they do in a paper care plan.
  Widget _numbered(CarePlanDiagnosis r, TextTheme text,
      {required bool rationale}) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      mainAxisSize: MainAxisSize.min,
      children: [
        for (var j = 0; j < r.interventions.length; j++)
          Padding(
            padding: EdgeInsets.only(
                bottom: j == r.interventions.length - 1 ? 0 : 8),
            child: Text(
              '${j + 1}. ${rationale ? r.interventions[j].rationale : r.interventions[j].action}',
              style: text.bodySmall,
            ),
          ),
      ],
    );
  }
}

/// A padded table cell. Inside a [Table] the child may be any height, so the row
/// grows to fit — no fixed-height clipping like [DataTable].
class _CellBox extends StatelessWidget {
  const _CellBox({required this.child});
  final Widget child;

  @override
  Widget build(BuildContext context) => Padding(
        padding: const EdgeInsets.symmetric(vertical: 10, horizontal: 10),
        child: child,
      );
}

// ─────────────────────────────────────────────────────────────────────────────
// Collapsible reference: what a nursing care plan is and how to individualize
// it. Sourced from the standard NCP components / objectives.
// ─────────────────────────────────────────────────────────────────────────────
class _AboutCarePlans extends StatelessWidget {
  const _AboutCarePlans();

  static const _body = '''
### Components
A nursing care plan (NCP) includes **assessment**, a **nursing diagnosis**,
**expected outcomes**, **nursing interventions**, **rationales**, and
**evaluation**.

- **Assessment** — physical, emotional, psychosocial, cultural, spiritual,
  cognitive, functional, age-related, economic and environmental data, both
  subjective and objective.
- **Nursing diagnosis** — a statement of the patient's health issue based on the
  assessment.
- **Expected outcomes** — specific short- and long-term goals achieved through
  interventions.
- **Nursing interventions** — evidence-based actions that address the diagnosis.
- **Rationales** — the evidence-based reasons for each intervention.
- **Evaluation** — how progress is monitored and the plan adjusted as the
  patient's status and goals change.

### Digital & AI-assisted care plans
Modern EHRs increasingly auto-suggest diagnoses from real-time labs and vitals,
and nurses use AI tools to draft plans. Keep the **"Human in the Loop"**
standard: every AI-generated diagnosis or intervention must be validated by the
nurse against hospital policy and the patient's specific condition — AI models
can produce hallucinations.

### Individualizing the plan
- Perform a comprehensive assessment of health, history, status and goals.
- Involve the patient in planning to align care with their goals and improve
  engagement and compliance.
- Reassess and evaluate continuously; adjust as health and goals change.

### Objectives
Promote evidence-based, holistic care; establish care pathways and care bundles;
identify and distinguish goals and expected outcomes; review communication and
documentation; and measure nursing care.
''';

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;
    final text = Theme.of(context).textTheme;
    return Theme(
      data: Theme.of(context).copyWith(dividerColor: Colors.transparent),
      child: GlassCard(
        padding: EdgeInsets.zero,
        child: ExpansionTile(
          tilePadding: const EdgeInsets.symmetric(horizontal: 18),
          childrenPadding:
              const EdgeInsets.fromLTRB(18, 0, 18, 18),
          leading: Icon(Icons.info_outline, color: scheme.primary),
          title: Text('About care plans',
              style: text.titleSmall
                  ?.copyWith(fontWeight: FontWeight.w700)),
          children: [
            MarkdownBody(
              data: _body,
              styleSheet: MarkdownStyleSheet(
                p: text.bodyMedium,
                h3: text.titleSmall?.copyWith(color: scheme.primary),
                strong: const TextStyle(fontWeight: FontWeight.w700),
                listBullet: text.bodyMedium,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
