import 'package:flutter/material.dart';

import 'anatomy_models.dart';

/// All bundled anatomy diagrams. Each has a real public-domain / CC-BY
/// illustration ([imageAsset], fetched by `tool/fetch_anatomy_images.py`) with
/// the vector painter in `anatomy_painters.dart` kept as a fallback.
///
/// The const coordinates below were tuned to the old vector art; on the real
/// images they're re-pinned in-app via the calibrate screen (drag the markers,
/// Save, then "Copy Dart" to paste the new values back here). `credit` strings
/// are provisional — verify against the fetcher's printed attribution.
const List<AnatomyDiagram> kAnatomyDiagrams = [
  AnatomyDiagram(
    id: 'heart',
    name: 'The Heart',
    system: 'Cardiovascular',
    icon: Icons.favorite_border,
    imageAsset: 'assets/images/anatomy/heart.png',
    credit: 'Wapcaplet · CC BY-SA 3.0 · Wikimedia Commons',
    parts: [
      AnatomyPart('Superior vena cava', .36, .12, accepted: ['svc']),
      AnatomyPart('Aorta', .54, .06),
      AnatomyPart('Pulmonary artery', .65, .12, accepted: ['pulmonary trunk']),
      AnatomyPart('Right atrium', .33, .44),
      AnatomyPart('Left atrium', .67, .44),
      AnatomyPart('Right ventricle', .36, .70),
      AnatomyPart('Left ventricle', .62, .72),
      AnatomyPart('Inferior vena cava', .16, .66, accepted: ['ivc']),
      AnatomyPart('Septum', .50, .60, accepted: ['interventricular septum']),
    ],
  ),
  AnatomyDiagram(
    id: 'neuron',
    name: 'The Neuron',
    system: 'Nervous',
    icon: Icons.hub_outlined,
    imageAsset: 'assets/images/anatomy/neuron.png',
    credit: 'BruceBlaus · CC BY 3.0 · Wikimedia Commons',
    parts: [
      AnatomyPart('Dendrites', .05, .30, accepted: ['dendrite']),
      AnatomyPart('Cell body', .18, .64, accepted: ['soma', 'perikaryon']),
      AnatomyPart('Nucleus', .18, .47),
      AnatomyPart('Axon', .62, .45),
      AnatomyPart('Myelin sheath', .40, .58, accepted: ['myelin']),
      AnatomyPart('Node of Ranvier', .47, .50),
      AnatomyPart('Axon terminals', .90, .50,
          accepted: ['axon terminal', 'synaptic terminals']),
    ],
  ),
  AnatomyDiagram(
    id: 'skin',
    name: 'The Skin (Integument)',
    system: 'Integumentary',
    icon: Icons.layers_outlined,
    imageAsset: 'assets/images/anatomy/skin.png',
    credit: 'BruceBlaus · CC BY 3.0 · Wikimedia Commons',
    parts: [
      AnatomyPart('Epidermis', .80, .20),
      AnatomyPart('Dermis', .80, .46),
      AnatomyPart('Hypodermis', .80, .78,
          accepted: ['subcutaneous layer', 'subcutis']),
      AnatomyPart('Hair shaft', .30, .10, accepted: ['hair']),
      AnatomyPart('Hair follicle', .30, .80, accepted: ['follicle']),
      AnatomyPart('Sweat gland', .62, .80,
          accepted: ['sudoriferous gland']),
    ],
  ),
  AnatomyDiagram(
    id: 'long_bone',
    name: 'The Long Bone',
    system: 'Skeletal',
    icon: Icons.straighten,
    imageAsset: 'assets/images/anatomy/long_bone.png',
    credit: 'Public domain · Wikimedia Commons',
    parts: [
      AnatomyPart('Proximal epiphysis', .50, .15,
          accepted: ['epiphysis']),
      AnatomyPart('Diaphysis', .42, .50, accepted: ['shaft']),
      AnatomyPart('Medullary cavity', .52, .45,
          accepted: ['marrow cavity']),
      AnatomyPart('Distal epiphysis', .50, .85),
      AnatomyPart('Periosteum', .59, .55),
    ],
  ),
  AnatomyDiagram(
    id: 'eye',
    name: 'The Eye',
    system: 'Special Senses',
    icon: Icons.visibility_outlined,
    imageAsset: 'assets/images/anatomy/eye.png',
    credit: 'Holly Fischer · CC BY 3.0 · Wikimedia Commons',
    parts: [
      AnatomyPart('Cornea', .06, .50),
      AnatomyPart('Iris', .20, .34),
      AnatomyPart('Pupil', .15, .50),
      AnatomyPart('Lens', .27, .50),
      AnatomyPart('Retina', .78, .64),
      AnatomyPart('Optic nerve', .96, .50),
      AnatomyPart('Sclera', .50, .13),
    ],
  ),
  AnatomyDiagram(
    id: 'respiratory',
    name: 'The Respiratory System',
    system: 'Respiratory',
    icon: Icons.air,
    imageAsset: 'assets/images/anatomy/respiratory.png',
    credit: 'Public domain · Wikimedia Commons',
    parts: [
      AnatomyPart('Trachea', .50, .22, accepted: ['windpipe']),
      AnatomyPart('Bronchus', .64, .52, accepted: ['bronchi', 'main bronchus']),
      AnatomyPart('Left lung', .22, .70),
      AnatomyPart('Right lung', .78, .70),
      AnatomyPart('Diaphragm', .50, .92),
    ],
  ),
  AnatomyDiagram(
    id: 'digestive',
    name: 'The Digestive System',
    system: 'Gastrointestinal',
    icon: Icons.restaurant_outlined,
    imageAsset: 'assets/images/anatomy/digestive.png',
    credit: 'Mariana Ruiz, Jmarchn · Public domain · Wikimedia Commons',
    parts: [
      AnatomyPart('Esophagus', .46, .18, accepted: ['oesophagus']),
      AnatomyPart('Stomach', .37, .46),
      AnatomyPart('Liver', .70, .33),
      AnatomyPart('Large intestine', .31, .72,
          accepted: ['colon', 'large bowel']),
      AnatomyPart('Small intestine', .50, .68, accepted: ['small bowel']),
    ],
  ),
  AnatomyDiagram(
    id: 'nephron',
    name: 'The Nephron',
    system: 'Renal',
    icon: Icons.water_drop_outlined,
    imageAsset: 'assets/images/anatomy/nephron.png',
    credit: 'Madhero88 · CC BY 3.0 · Wikimedia Commons',
    parts: [
      AnatomyPart('Glomerulus', .22, .24),
      AnatomyPart("Bowman's capsule", .11, .24,
          accepted: ['bowman capsule', 'glomerular capsule']),
      AnatomyPart('Proximal convoluted tubule', .40, .24,
          accepted: ['pct', 'proximal tubule']),
      AnatomyPart('Loop of Henle', .57, .68, accepted: ['nephron loop']),
      AnatomyPart('Distal convoluted tubule', .72, .27,
          accepted: ['dct', 'distal tubule']),
      AnatomyPart('Collecting duct', .84, .72),
    ],
  ),
  AnatomyDiagram(
    id: 'heart_valves',
    name: 'Heart Valves',
    system: 'Cardiovascular',
    icon: Icons.favorite,
    imageAsset: 'assets/images/anatomy/heart_valves.png',
    credit: "Henry Vandyke Carter, Gray's Anatomy · Public domain",
    parts: [
      AnatomyPart('Pulmonary valve', .50, .22,
          accepted: ['pulmonic valve']),
      AnatomyPart('Aortic valve', .44, .42),
      AnatomyPart('Tricuspid valve', .66, .60,
          accepted: ['right atrioventricular valve']),
      AnatomyPart('Mitral valve', .36, .64,
          accepted: ['bicuspid valve', 'left atrioventricular valve']),
    ],
  ),
  AnatomyDiagram(
    id: 'blood_vessel',
    name: 'Blood Vessels',
    system: 'Cardiovascular',
    icon: Icons.timeline,
    imageAsset: 'assets/images/anatomy/blood_vessel.png',
    credit: 'OpenStax College · CC BY 3.0 · Wikimedia Commons',
    parts: [
      AnatomyPart('Artery', .50, .22),
      AnatomyPart('Vein', .50, .52),
      AnatomyPart('Valve', .60, .52, accepted: ['venous valve']),
      AnatomyPart('Capillary', .50, .82),
    ],
  ),
  AnatomyDiagram(
    id: 'urinary_system',
    name: 'The Urinary System',
    system: 'Renal',
    icon: Icons.water_drop,
    imageAsset: 'assets/images/anatomy/urinary_system.png',
    credit: 'Arcadian · Public domain · Wikimedia Commons',
    parts: [
      AnatomyPart('Adrenal gland', .30, .17,
          accepted: ['suprarenal gland']),
      AnatomyPart('Kidney', .30, .28),
      AnatomyPart('Ureter', .40, .55),
      AnatomyPart('Urinary bladder', .50, .80, accepted: ['bladder']),
      AnatomyPart('Urethra', .50, .94),
    ],
  ),
  AnatomyDiagram(
    id: 'kidney',
    name: 'Kidney Anatomy',
    system: 'Renal',
    icon: Icons.spa_outlined,
    imageAsset: 'assets/images/anatomy/kidney.png',
    credit: 'BruceBlaus · CC BY 3.0 · Wikimedia Commons',
    parts: [
      AnatomyPart('Renal cortex', .70, .22, accepted: ['cortex']),
      AnatomyPart('Renal medulla', .66, .50,
          accepted: ['medulla', 'renal pyramid', 'pyramid']),
      AnatomyPart('Renal pelvis', .46, .50, accepted: ['pelvis']),
      AnatomyPart('Ureter', .20, .58),
      AnatomyPart('Renal capsule', .82, .50, accepted: ['capsule']),
    ],
  ),
  AnatomyDiagram(
    id: 'fetal_skull',
    name: 'The Fetal Skull',
    system: 'Maternal & Newborn',
    icon: Icons.child_care,
    imageAsset: 'assets/images/anatomy/fetal_skull.png',
    credit: "Henry Vandyke Carter, Gray's Anatomy · Public domain",
    parts: [
      AnatomyPart('Anterior fontanelle', .50, .37,
          accepted: ['bregma', 'anterior fontanel']),
      AnatomyPart('Posterior fontanelle', .50, .635,
          accepted: ['lambda', 'posterior fontanel']),
      AnatomyPart('Sagittal suture', .50, .50),
      AnatomyPart('Coronal suture', .30, .36),
      AnatomyPart('Lambdoid suture', .34, .64),
      AnatomyPart('Frontal bone', .50, .16),
      AnatomyPart('Parietal bone', .72, .50),
    ],
  ),
];
